// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ReactHotToast from "react-hot-toast";
import * as JsxRuntime from "react/jsx-runtime";

var Toaster = {};

function Container(props) {
  return JsxRuntime.jsxs("main", {
              children: [
                JsxRuntime.jsx(ReactHotToast.Toaster, {}),
                JsxRuntime.jsx("div", {
                      children: props.children,
                      className: "bg-white/90 h-[84vh] rounded-md p-3 overflow-hidden"
                    })
              ],
              className: "absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 max-w-[31rem] max-h-[96vh] overflow-hidden w-full mx-auto p-3"
            });
}

var make = Container;

export {
  Toaster ,
  make ,
}
/* react-hot-toast Not a pure module */
