// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Container(props) {
  return JsxRuntime.jsx("main", {
              children: JsxRuntime.jsx("div", {
                    children: props.children,
                    className: "bg-background min-h-[78vh] rounded-md h-full p-6"
                  }),
              className: "absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 max-w-[31rem] w-full mx-auto p-6"
            });
}

var make = Container;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
