// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Button from "../ui/Button.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as ReactAriaComponents from "react-aria-components";

var TextArea = {};

function FormCreateTask(props) {
  var match = React.useState(function () {
        return "";
      });
  var setText = match[1];
  var text = match[0];
  var handleInputChange = function ($$event) {
    var value = $$event.currentTarget.value;
    setText(function (param) {
          return value;
        });
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Create New Task Todo",
                      className: "text-2xl text-primary"
                    }),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsxs("form", {
                      children: [
                        JsxRuntime.jsx("label", {
                              children: "Task:",
                              htmlFor: "task"
                            }),
                        JsxRuntime.jsx("br", {}),
                        JsxRuntime.jsx(ReactAriaComponents.TextArea, {
                              label: "Todo:",
                              name: "task",
                              className: "h-32 p-2 w-full border",
                              maxLength: 120,
                              value: text,
                              onChange: handleInputChange
                            }),
                        JsxRuntime.jsx("br", {}),
                        JsxRuntime.jsx("br", {}),
                        JsxRuntime.jsx(Button.make, {
                              onClick: (function (param) {
                                  console.log(text);
                                }),
                              children: "Save"
                            })
                      ]
                    })
              ]
            });
}

var make = FormCreateTask;

export {
  TextArea ,
  make ,
}
/* react Not a pure module */
