// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "../../lib/Utils.res.mjs";
import * as Button from "../ui/Button.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Title(props) {
  var task = props.task;
  var now = new Date();
  var match = now.getDay();
  var today = match < 3.0 ? (
      match !== 0.0 ? (
          match !== 1.0 ? (
              match !== 2.0 ? "Unknown" : "Tuesday"
            ) : "Monday"
        ) : "Sunday"
    ) : (
      match < 5.0 ? (
          match !== 3.0 ? (
              match !== 4.0 ? "Unknown" : "Thursday"
            ) : "Wednesday"
        ) : (
          match !== 5.0 ? (
              match !== 6.0 ? "Unknown" : "Saturday"
            ) : "Friday"
        )
    );
  var todayDate = now.getDate();
  var match$1 = now.getMonth();
  var month = match$1 < 6.0 ? (
      match$1 < 3.0 ? (
          match$1 !== 0.0 ? (
              match$1 !== 1.0 ? (
                  match$1 !== 2.0 ? "Invalid month number" : "March"
                ) : "February"
            ) : "January"
        ) : (
          match$1 !== 3.0 ? (
              match$1 !== 4.0 ? (
                  match$1 !== 5.0 ? "Invalid month number" : "June"
                ) : "May"
            ) : "April"
        )
    ) : (
      match$1 < 9.0 ? (
          match$1 !== 6.0 ? (
              match$1 !== 7.0 ? (
                  match$1 !== 8.0 ? "Invalid month number" : "September"
                ) : "August"
            ) : "July"
        ) : (
          match$1 !== 9.0 ? (
              match$1 !== 10.0 ? (
                  match$1 !== 11.0 ? "Invalid month number" : "December"
                ) : "November"
            ) : "October"
        )
    );
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("h2", {
                              children: [
                                JsxRuntime.jsx("span", {
                                      children: today,
                                      className: "font-semibold text-3xl text-indigo-500"
                                    }),
                                JsxRuntime.jsx("span", {
                                      children: ", " + todayDate.toString() + " " + Utils.getOrdinalSuffix(todayDate),
                                      className: "font-normal text-2xl text-indigo-500"
                                    }),
                                JsxRuntime.jsx("br", {}),
                                JsxRuntime.jsx("span", {
                                      children: month,
                                      className: "font-normal text-base text-gray-500"
                                    })
                              ],
                              className: "leading-7"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("span", {
                                      children: task.toString(),
                                      className: "font-medium"
                                    }),
                                JsxRuntime.jsx("span", {
                                      children: " " + (
                                        task > 1 ? "Tasks" : "Task"
                                      ),
                                      className: "font-normal"
                                    })
                              ],
                              className: "text-gray-500 text-lg mr-3"
                            })
                      ],
                      className: "flex flex-row justify-between items-center w-full"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              className: "w-[150%] -left-6 absolute top-1/2 -translate-y-1/2 h-[1px] bg-black/10"
                            }),
                        JsxRuntime.jsxs(Button.make, {
                              className: Utils.cn([
                                    "absolute right-2 top-1/2 -translate-y-1/2 rounded-full z-10 py-7 px-[0.65rem]",
                                    "bg-red-400 text-white",
                                    "active:scale-105 active:ring-4 focus:ring-4",
                                    "hover:bg-red-600"
                                  ]),
                              onClick: (function (param) {
                                  console.log("Tambah");
                                }),
                              children: [
                                JsxRuntime.jsx("span", {
                                      children: "Add new task",
                                      className: "sr-only"
                                    }),
                                JsxRuntime.jsxs("svg", {
                                      children: [
                                        JsxRuntime.jsx("path", {
                                              d: "M0 0h24v24H0z",
                                              fill: "none",
                                              stroke: "none"
                                            }),
                                        JsxRuntime.jsx("path", {
                                              d: "M12 5l0 14"
                                            }),
                                        JsxRuntime.jsx("path", {
                                              d: "M5 12l14 0"
                                            })
                                      ],
                                      className: "w-9 h-9",
                                      height: "44",
                                      width: "44",
                                      fill: "none",
                                      stroke: "currentColor",
                                      strokeLinecap: "round",
                                      strokeLinejoin: "round",
                                      strokeWidth: "1.5",
                                      viewBox: "0 0 24 24",
                                      xmlns: "http://www.w3.org/2000/svg"
                                    })
                              ]
                            })
                      ],
                      className: "text-right mt-9 relative mb-20"
                    })
              ]
            });
}

var make = Title;

export {
  make ,
}
/* Utils Not a pure module */
