// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Title from "./components/layout/Title.res.mjs";
import * as Container from "./components/layout/Container.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsx(Container.make, {
              children: JsxRuntime.jsx(Title.make, {
                    task: 12
                  })
            });
}

var make = App;

export {
  make ,
}
/* Title Not a pure module */
