// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "../../lib/Utils.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as ReactAriaComponents from "react-aria-components";

var ReactAriaButton = {};

function variantClass(v) {
  switch (v) {
    case "Default" :
        return "bg-primary text-primary-foreground hover:bg-indigo-600";
    case "Destructive" :
        return "bg-destructive text-destructive-foreground hover:bg-destructive/90";
    case "Outline" :
        return "border border-input hover:bg-accent hover:text-accent-foreground";
    case "Secondary" :
        return "bg-secondary text-secondary-foreground hover:bg-secondary/80";
    case "Ghost" :
        return "hover:bg-accent hover:text-accent-foreground";
    case "Link" :
        return "underline-offset-4 hover:underline text-primary";
    
  }
}

function sizeClass(s) {
  switch (s) {
    case "Default" :
        return "h-10 py-2 px-4";
    case "Sm" :
        return "h-9 px-3 rounded-md";
    case "Lg" :
        return "h-11 px-8 rounded-md";
    case "Icon" :
        return "h-10 w-10";
    
  }
}

function Button(props) {
  var __size = props.size;
  var __variant = props.variant;
  var className = props.className;
  var variant = __variant !== undefined ? __variant : "Default";
  var size = __size !== undefined ? __size : "Default";
  var classNames = Utils.cn([
        "inline-flex items-center justify-center rounded-md text-base font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:opacity-50 disabled:pointer-events-none ring-offset-background",
        variantClass(variant),
        sizeClass(size),
        className !== undefined ? className : ""
      ]);
  return JsxRuntime.jsx(ReactAriaComponents.Button, {
              children: props.children,
              className: classNames,
              onPress: props.onClick
            });
}

var make = Button;

export {
  ReactAriaButton ,
  variantClass ,
  sizeClass ,
  make ,
}
/* Utils Not a pure module */
