// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import * as ReactAriaComponents from "react-aria-components";

import './Checkbox.css'
;

var ReactAriaCheckbox = {};

function TaskCardView(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs(ReactAriaComponents.Checkbox, {
                    children: [
                      JsxRuntime.jsx("div", {
                            children: JsxRuntime.jsx("svg", {
                                  children: JsxRuntime.jsx("polyline", {
                                        points: "1 9 7 14 15 4"
                                      }),
                                  "aria-hidden": true,
                                  viewBox: "0 0 18 18"
                                }),
                            className: "checkbox"
                          }),
                      JsxRuntime.jsx("span", {
                            children: props.text,
                            className: "flex-grow"
                          }),
                      JsxRuntime.jsx("time", {
                            children: "07:30",
                            className: "flex-shrink-0 w-16 text-sm font-medium text-gray-400"
                          })
                    ],
                    checked: props.checked,
                    onChange: props.onChange,
                    className: "react-aria-Checkbox"
                  }),
              className: "my-3 pb-6 pt-3 border-b"
            });
}

var make = TaskCardView;

export {
  ReactAriaCheckbox ,
  make ,
}
/*  Not a pure module */
